# Housing Days On Market Wrangling For School Digger Data

## Python Package(s) Used

In [1]:
#import datetime as dt
#import dill
#import json
import numpy as np
#import os
import pandas as pd
#import requests
#import time

## Data Fetching

In [21]:
# Read the elementary school data into DataFrames
df_elem_2009_10 = pd.read_excel('./2009-10/elementary_schooldigger_280219227.xlsx', skiprows=4)
df_elem_2010_11 = pd.read_excel('./2010-11/elementary_schooldigger_1592209945.xlsx', skiprows=4)
df_elem_2011_12 = pd.read_excel('./2011-12/elementary_schooldigger_1878616835.xlsx', skiprows=4)
#df_elem_2012_13 = pd.read_excel('./2012-13/elementary_schooldigger_.xlsx', skiprows=4)
df_elem_2013_14 = pd.read_excel('./2013-14/elementary_schooldigger_31840482.xlsx', skiprows=4)
df_elem_2014_15 = pd.read_excel('./2014-15/elementary_schooldigger_1650135798.xlsx', skiprows=4)
df_elem_2015_16 = pd.read_excel('./2015-16/schooldigger_ Elementary School Ranking.xlsx', skiprows=4)

# Read the middle school data into DataFrames
df_middle_2009_10 = pd.read_excel('./2009-10/schooldigger_middleschool_2009-2010.xlsx', skiprows=4)
df_middle_2010_11 = pd.read_excel('./2010-11/schooldigger_middleschool_2010-2011.xlsx', skiprows=4)
df_middle_2011_12 = pd.read_excel('./2011-12/schooldigger_middleschool_2011-2012.xlsx', skiprows=4)
#df_middle_2012_13 = pd.read_excel('./2012-13/elementary_schooldigger_.xlsx', skiprows=4)
df_middle_2013_14 = pd.read_excel('./2013-14/schooldigger_middleschool_2013-2014.xlsx', skiprows=4)
df_middle_2014_15 = pd.read_excel('./2014-15/schooldigger_middleschool_2014-2015.xlsx', skiprows=4)
df_middle_2015_16 = pd.read_excel('./2015-16/schooldigger_ Middle School Ranking.xlsx', skiprows=4)

# Read the high school data into DataFrames
df_high_2009_10 = pd.read_excel('./2009-10/schooldigger_highschool_2009-2010.xlsx', skiprows=4)
df_high_2010_11 = pd.read_excel('./2010-11/schooldigger_highschools_2010_2011.xlsx', skiprows=4)
df_high_2011_12 = pd.read_excel('./2011-12/schooldigger_highschool_2012-2011.xlsx', skiprows=4)
#df_middle_2012_13 = pd.read_excel('./2012-13/elementary_schooldigger_.xlsx', skiprows=4)
df_high_2013_14 = pd.read_excel('./2013-14/schooldigger_Highschool_2014-2013.xlsx', skiprows=4)
df_high_2014_15 = pd.read_excel('./2014-15/schooldigger_Highschool_2015-2014.xlsx', skiprows=4)
df_high_2015_16 = pd.read_excel('./2015-16/schooldigger_Highschool - School Ranking.xlsx', skiprows=4)

## Data Wrangling

In [22]:
df_elem_2009_10.head()

,Rank (2009-10),School,School URL,District,District URL,City,City URL,Zip,County,Low Grade,...,Percent Asian,Percent Hispanic,Percent Pacific Islander,Percent Two or More Races,Percent White,Average Standard Score (2009-10),Average Standard Score (-),Rank (-),Rank Change from (-),SchoolDigger Star Rating
0,1,Key Elementary School,https://www.schooldigger.com/go/DC/schools/000...,District Of Columbia Public Schools,https://www.schooldigger.com/go/DC/district/00...,Washington,https://www.schooldigger.com/go/DC/city/Washin...,20016,District Of Columbia,PK,...,9.6 %,8.2 %,NaN,NaN,73.8 %,98.3,NaN,NaN,NaN,5
1,2,Mann Elementary School,https://www.schooldigger.com/go/DC/schools/000...,District Of Columbia Public Schools,https://www.schooldigger.com/go/DC/district/00...,Washington,https://www.schooldigger.com/go/DC/city/Washin...,20016,District Of Columbia,PK,...,6.7 %,6.3 %,NaN,NaN,78.8 %,98.1,NaN,NaN,NaN,5
2,3,Stoddert Elementary School,https://www.schooldigger.com/go/DC/schools/000...,District Of Columbia Public Schools,https://www.schooldigger.com/go/DC/district/00...,Washington,https://www.schooldigger.com/go/DC/city/Washin...,20007,District Of Columbia,PK,...,11.6 %,8.8 %,NaN,NaN,60.4 %,97.9,NaN,NaN,NaN,5
3,4,Janney Elementary School,https://www.schooldigger.com/go/DC/schools/000...,District Of Columbia Public Schools,https://www.schooldigger.com/go/DC/district/00...,Washington,https://www.schooldigger.com/go/DC/city/Washin...,20016,District Of Columbia,PK,...,6.1 %,5.6 %,NaN,NaN,73.6 %,97.8,NaN,NaN,NaN,5
4,5,St Coletta Special Education Pcs,https://www.schooldigger.com/go/DC/schools/000...,St Coletta Special Education Pcs,https://www.schooldigger.com/go/DC/district/00...,Washington,https://www.schooldigger.com/go/DC/city/Washin...,20003,District Of Columbia,PK,...,0.0 %,6.2 %,NaN,NaN,5.3 %,97.2,NaN,NaN,NaN,5

In [23]:
# Rename columns to aid in row appending dataframes together
df_elem_2009_10 = df_elem_2009_10.rename(columns = {'Rank (2009-10)':'Rank'})
df_elem_2009_10 = df_elem_2009_10.rename(columns = {'Average Standard Score (2009-10)':'Average Standard Score'})
df_elem_2009_10 = df_elem_2009_10.rename(columns = {'Rank Change from (-)':'Rank Change from Prior Year'})

df_elem_2010_11 = df_elem_2010_11.rename(columns = {'Rank (2010-11)':'Rank'})
df_elem_2010_11 = df_elem_2010_11.rename(columns = {'Average Standard Score (2010-11)':'Average Standard Score'})
df_elem_2010_11 = df_elem_2010_11.rename(columns = {'Rank Change from (2009-10)':'Rank Change from Prior Year'})

df_elem_2011_12 = df_elem_2011_12.rename(columns = {'Rank (2011-12)':'Rank'})
df_elem_2011_12 = df_elem_2011_12.rename(columns = {'Average Standard Score (2011-12)':'Average Standard Score'})
df_elem_2011_12 = df_elem_2011_12.rename(columns = {'Rank Change from (2010-11)':'Rank Change from Prior Year'})

# Data for 2012-2013 not present! Raw data file shows they skipped a year. 

df_elem_2013_14 = df_elem_2013_14.rename(columns = {'Rank (2013-14)':'Rank'})
df_elem_2013_14 = df_elem_2013_14.rename(columns = {'Average Standard Score (2013-14)':'Average Standard Score'})
df_elem_2013_14 = df_elem_2013_14.rename(columns = {'Rank Change from (2011-12)':'Rank Change from Prior Year'})

df_elem_2014_15 = df_elem_2014_15.rename(columns = {'Rank (2014-15)':'Rank'})
df_elem_2014_15 = df_elem_2014_15.rename(columns = {'Average Standard Score (2014-15)':'Average Standard Score'})
df_elem_2014_15 = df_elem_2014_15.rename(columns = {'Rank Change from (2013-14)':'Rank Change from Prior Year'})

df_elem_2015_16 = df_elem_2015_16.rename(columns = {'Rank (2015-16)':'Rank'})
df_elem_2015_16 = df_elem_2015_16.rename(columns = {'Average Standard Score (2015-16)':'Average Standard Score'})
df_elem_2015_16 = df_elem_2015_16.rename(columns = {'Rank Change from (2014-15)':'Rank Change from Prior Year'})

In [24]:
# Rename columns to aid in row appending dataframes together
df_middle_2009_10 = df_middle_2009_10.rename(columns = {'Rank (2009-10)':'Rank'})
df_middle_2009_10 = df_middle_2009_10.rename(columns = {'Average Standard Score (2009-10)':'Average Standard Score'})
df_middle_2009_10 = df_middle_2009_10.rename(columns = {'Rank Change from (-)':'Rank Change from Prior Year'})

# Dataset for 2010-11 contains mislabelling of date-year
df_middle_2010_11 = df_middle_2010_11.rename(columns = {'Rank (2011-12)':'Rank'})
df_middle_2010_11 = df_middle_2010_11.rename(columns = {'Average Standard Score (2011-12)':'Average Standard Score'})
df_middle_2010_11 = df_middle_2010_11.rename(columns = {'Rank Change from (2010-11)':'Rank Change from Prior Year'})

df_middle_2011_12 = df_middle_2011_12.rename(columns = {'Rank (2011-12)':'Rank'})
df_middle_2011_12 = df_middle_2011_12.rename(columns = {'Average Standard Score (2011-12)':'Average Standard Score'})
df_middle_2011_12 = df_middle_2011_12.rename(columns = {'Rank Change from (2010-11)':'Rank Change from Prior Year'})

# Data for 2012-2013 not present! Raw data file shows they skipped a year. 

df_middle_2013_14 = df_middle_2013_14.rename(columns = {'Rank (2013-14)':'Rank'})
df_middle_2013_14 = df_middle_2013_14.rename(columns = {'Average Standard Score (2013-14)':'Average Standard Score'})
df_middle_2013_14 = df_middle_2013_14.rename(columns = {'Rank Change from (2011-12)':'Rank Change from Prior Year'})

df_middle_2014_15 = df_middle_2014_15.rename(columns = {'Rank (2014-15)':'Rank'})
df_middle_2014_15 = df_middle_2014_15.rename(columns = {'Average Standard Score (2014-15)':'Average Standard Score'})
df_middle_2014_15 = df_middle_2014_15.rename(columns = {'Rank Change from (2013-14)':'Rank Change from Prior Year'})

df_middle_2015_16 = df_middle_2015_16.rename(columns = {'Rank (2015-16)':'Rank'})
df_middle_2015_16 = df_middle_2015_16.rename(columns = {'Average Standard Score (2015-16)':'Average Standard Score'})
df_middle_2015_16 = df_middle_2015_16.rename(columns = {'Rank Change from (2014-15)':'Rank Change from Prior Year'})

In [25]:
# Rename columns to aid in row appending dataframes together
df_high_2009_10 = df_high_2009_10.rename(columns = {'Rank (2009-10)':'Rank'})
df_high_2009_10 = df_high_2009_10.rename(columns = {'Average Standard Score (2009-10)':'Average Standard Score'})
df_high_2009_10 = df_high_2009_10.rename(columns = {'Rank Change from (-)':'Rank Change from Prior Year'})

df_high_2010_11 = df_high_2010_11.rename(columns = {'Rank (2010-11)':'Rank'})
df_high_2010_11 = df_high_2010_11.rename(columns = {'Average Standard Score (2010-11)':'Average Standard Score'})
df_high_2010_11 = df_high_2010_11.rename(columns = {'Rank Change from (2009-10)':'Rank Change from Prior Year'})

df_high_2011_12 = df_high_2011_12.rename(columns = {'Rank (2011-12)':'Rank'})
df_high_2011_12 = df_high_2011_12.rename(columns = {'Average Standard Score (2011-12)':'Average Standard Score'})
df_high_2011_12 = df_high_2011_12.rename(columns = {'Rank Change from (2010-11)':'Rank Change from Prior Year'})

# Data for 2012-2013 not present! Raw data file shows they skipped a year. 

df_high_2013_14 = df_high_2013_14.rename(columns = {'Rank (2013-14)':'Rank'})
df_high_2013_14 = df_high_2013_14.rename(columns = {'Average Standard Score (2013-14)':'Average Standard Score'})
df_high_2013_14 = df_high_2013_14.rename(columns = {'Rank Change from (2011-12)':'Rank Change from Prior Year'})

df_high_2014_15 = df_high_2014_15.rename(columns = {'Rank (2014-15)':'Rank'})
df_high_2014_15 = df_high_2014_15.rename(columns = {'Average Standard Score (2014-15)':'Average Standard Score'})
df_high_2014_15 = df_high_2014_15.rename(columns = {'Rank Change from (2013-14)':'Rank Change from Prior Year'})

df_high_2015_16 = df_high_2015_16.rename(columns = {'Rank (2015-16)':'Rank'})
df_high_2015_16 = df_high_2015_16.rename(columns = {'Average Standard Score (2015-16)':'Average Standard Score'})
df_high_2015_16 = df_high_2015_16.rename(columns = {'Rank Change from (2014-15)':'Rank Change from Prior Year'})

In [26]:
# Add year column for ranking
df_elem_2009_10.insert(loc = 1, column = 'Rank_Year', value = '2009-10')
df_elem_2010_11.insert(loc = 1, column = 'Rank_Year', value = '2010-11')
df_elem_2011_12.insert(loc = 1, column = 'Rank_Year', value = '2011-12')
# df_elem_2012_13['Rank_Year'] = '2012-13'
df_elem_2013_14.insert(loc = 1, column = 'Rank_Year', value = '2013-14')
df_elem_2014_15.insert(loc = 1, column = 'Rank_Year', value = '2014-15')
df_elem_2015_16.insert(loc = 1, column = 'Rank_Year', value = '2015-16')
df_elem_2015_16.insert(loc = 15, column = 'Is Virtual', value = 'nan')

In [27]:
# Add year column for ranking
df_middle_2009_10.insert(loc = 1, column = 'Rank_Year', value = '2009-10')
df_middle_2010_11.insert(loc = 1, column = 'Rank_Year', value = '2010-11')
df_middle_2011_12.insert(loc = 1, column = 'Rank_Year', value = '2011-12')
# df_middle_2012_13['Rank_Year'] = '2012-13'
df_middle_2013_14.insert(loc = 1, column = 'Rank_Year', value = '2013-14')
df_middle_2014_15.insert(loc = 1, column = 'Rank_Year', value = '2014-15')
df_middle_2015_16.insert(loc = 1, column = 'Rank_Year', value = '2015-16')
df_middle_2015_16.insert(loc = 15, column = 'Is Virtual', value = 'nan')

In [28]:
# Add year column for ranking
df_high_2009_10.insert(loc = 1, column = 'Rank_Year', value = '2009-10')
df_high_2010_11.insert(loc = 1, column = 'Rank_Year', value = '2010-11')
df_high_2011_12.insert(loc = 1, column = 'Rank_Year', value = '2011-12')
# df_high_2012_13['Rank_Year'] = '2012-13'
df_high_2013_14.insert(loc = 1, column = 'Rank_Year', value = '2013-14')
df_high_2014_15.insert(loc = 1, column = 'Rank_Year', value = '2014-15')
df_high_2015_16.insert(loc = 1, column = 'Rank_Year', value = '2015-16')
df_high_2015_16.insert(loc = 15, column = 'Is Virtual', value = 'nan')

In [29]:
# Drop columns that contain prior ranking information
df_elem_2009_10 = df_elem_2009_10.drop(u'Average Standard Score (-)', axis = 1)
df_elem_2009_10 = df_elem_2009_10.drop(u'Rank (-)', axis = 1)

df_elem_2010_11 = df_elem_2010_11.drop(u'Average Standard Score (2009-10)', axis = 1)
df_elem_2010_11 = df_elem_2010_11.drop(u'Rank (2009-10)', axis = 1)

df_elem_2011_12 = df_elem_2011_12.drop(u'Average Standard Score (2010-11)', axis = 1)
df_elem_2011_12 = df_elem_2011_12.drop(u'Rank (2010-11)', axis = 1)

#2012-2013 Data issue

df_elem_2013_14 = df_elem_2013_14.drop(u'Average Standard Score (2011-12)', axis = 1)
df_elem_2013_14 = df_elem_2013_14.drop(u'Rank (2011-12)', axis = 1)

df_elem_2014_15 = df_elem_2014_15.drop(u'Average Standard Score (2013-14)', axis = 1)
df_elem_2014_15 = df_elem_2014_15.drop(u'Rank (2013-14)', axis = 1)

df_elem_2015_16 = df_elem_2015_16.drop(u'Average Standard Score (2014-15)', axis = 1)
df_elem_2015_16 = df_elem_2015_16.drop(u'Rank (2014-15)', axis = 1)

In [30]:
# Drop columns that contain prior ranking information
df_middle_2009_10 = df_middle_2009_10.drop(u'Average Standard Score (-)', axis = 1)
df_middle_2009_10 = df_middle_2009_10.drop(u'Rank (-)', axis = 1)

df_middle_2010_11 = df_middle_2010_11.drop(u'Average Standard Score (2010-11)', axis = 1)
df_middle_2010_11 = df_middle_2010_11.drop(u'Rank (2010-11)', axis = 1)

df_middle_2011_12 = df_middle_2011_12.drop(u'Average Standard Score (2010-11)', axis = 1)
df_middle_2011_12 = df_middle_2011_12.drop(u'Rank (2010-11)', axis = 1)

#2012-2013 Data issue

df_middle_2013_14 = df_middle_2013_14.drop(u'Average Standard Score (2011-12)', axis = 1)
df_middle_2013_14 = df_middle_2013_14.drop(u'Rank (2011-12)', axis = 1)

df_middle_2014_15 = df_middle_2014_15.drop(u'Average Standard Score (2013-14)', axis = 1)
df_middle_2014_15 = df_middle_2014_15.drop(u'Rank (2013-14)', axis = 1)

df_middle_2015_16 = df_middle_2015_16.drop(u'Average Standard Score (2014-15)', axis = 1)
df_middle_2015_16 = df_middle_2015_16.drop(u'Rank (2014-15)', axis = 1)

In [31]:
# Drop columns that contain prior ranking information
df_high_2009_10 = df_high_2009_10.drop(u'Average Standard Score (-)', axis = 1)
df_high_2009_10 = df_high_2009_10.drop(u'Rank (-)', axis = 1)

df_high_2010_11 = df_high_2010_11.drop(u'Average Standard Score (2009-10)', axis = 1)
df_high_2010_11 = df_high_2010_11.drop(u'Rank (2009-10)', axis = 1)

df_high_2011_12 = df_high_2011_12.drop(u'Average Standard Score (2010-11)', axis = 1)
df_high_2011_12 = df_high_2011_12.drop(u'Rank (2010-11)', axis = 1)

#2012-2013 Data issue

df_high_2013_14 = df_high_2013_14.drop(u'Average Standard Score (2011-12)', axis = 1)
df_high_2013_14 = df_high_2013_14.drop(u'Rank (2011-12)', axis = 1)

df_high_2014_15 = df_high_2014_15.drop(u'Average Standard Score (2013-14)', axis = 1)
df_high_2014_15 = df_high_2014_15.drop(u'Rank (2013-14)', axis = 1)

df_high_2015_16 = df_high_2015_16.drop(u'Average Standard Score (2014-15)', axis = 1)
df_high_2015_16 = df_high_2015_16.drop(u'Rank (2014-15)', axis = 1)

In [32]:
print df_elem_2009_10.info()
print df_elem_2010_11.info()
print df_elem_2011_12.info()
print df_elem_2013_14.info()
print df_elem_2014_15.info()
print df_elem_2015_16.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 30 columns):
Rank                           109 non-null int64
Rank_Year                      109 non-null object
School                         109 non-null object
School URL                     109 non-null object
District                       109 non-null object
District URL                   109 non-null object
City                           109 non-null object
City URL                       109 non-null object
Zip                            109 non-null int64
County                         109 non-null object
Low Grade                      109 non-null object
High Grade                     109 non-null object
Is Title I                     109 non-null object
Is Charter                     109 non-null object
Is Magnet                      109 non-null object
Is Virtual                     109 non-null object
Number Students                109 non-null int64
Number Fulltime Teachers       108 non-null float64
Student/Teacher Ratio          108 non-null float64
Percent Free/Disc Lunch        107 non-null object
Percent African American       108 non-null object
Percent American Indian        108 non-null object
Percent Asian                  108 non-null object
Percent Hispanic               108 non-null object
Percent Pacific Islander       0 non-null float64
Percent Two or More Races      0 non-null float64
Percent White                  108 non-null object
Average Standard Score         109 non-null float64
Rank Change from Prior Year    0 non-null float64
SchoolDigger Star Rating       109 non-null int64
dtypes: float64(6), int64(4), object(20)
memory usage: 25.6+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 30 columns):
Rank                           109 non-null int64
Rank_Year                      109 non-null object
School                         109 non-null object
School URL                     109 non-null object
District                       109 non-null object
District URL                   109 non-null object
City                           109 non-null object
City URL                       109 non-null object
Zip                            109 non-null int64
County                         109 non-null object
Low Grade                      109 non-null object
High Grade                     109 non-null object
Is Title I                     109 non-null object
Is Charter                     109 non-null object
Is Magnet                      109 non-null object
Is Virtual                     109 non-null object
Number Students                109 non-null int64
Number Fulltime Teachers       105 non-null float64
Student/Teacher Ratio          105 non-null float64
Percent Free/Disc Lunch        107 non-null object
Percent African American       109 non-null object
Percent American Indian        109 non-null object
Percent Asian                  109 non-null object
Percent Hispanic               109 non-null object
Percent Pacific Islander       109 non-null object
Percent Two or More Races      109 non-null object
Percent White                  109 non-null object
Average Standard Score         109 non-null float64
Rank Change from Prior Year    108 non-null float64
SchoolDigger Star Rating       109 non-null int64
dtypes: float64(4), int64(4), object(22)
memory usage: 25.6+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 30 columns):
Rank                           110 non-null int64
Rank_Year                      110 non-null object
School                         110 non-null object
School URL                     110 non-null object
District                       110 non-null object
District URL                   110 non-null object
City                           110 non-null object
City URL                       110 non-null object
Zip                            110 non-null int64
County                         110 non-null object
Low Grade                      110 non-null object
High Grade                     110 non-null object
Is Title I                     110 non-null object
Is Charter                     110 non-null object
Is Magnet                      110 non-null object
Is Virtual                     110 non-null object
Number Students                110 non-null int64
Number Fulltime Teachers       109 non-null float64
Student/Teacher Ratio          109 non-null float64
Percent Free/Disc Lunch        109 non-null object
Percent African American       110 non-null object
Percent American Indian        110 non-null object
Percent Asian                  110 non-null object
Percent Hispanic               110 non-null object
Percent Pacific Islander       110 non-null object
Percent Two or More Races      110 non-null object
Percent White                  110 non-null object
Average Standard Score         110 non-null float64
Rank Change from Prior Year    108 non-null float64
SchoolDigger Star Rating       110 non-null int64
dtypes: float64(4), int64(4), object(22)
memory usage: 25.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 30 columns):
Rank                           107 non-null int64
Rank_Year                      107 non-null object
School                         107 non-null object
School URL                     107 non-null object
District                       107 non-null object
District URL                   107 non-null object
City                           107 non-null object
City URL                       107 non-null object
Zip                            107 non-null int64
County                         107 non-null object
Low Grade                      107 non-null object
High Grade                     107 non-null object
Is Title I                     107 non-null object
Is Charter                     107 non-null object
Is Magnet                      107 non-null object
Is Virtual                     107 non-null object
Number Students                107 non-null int64
Number Fulltime Teachers       106 non-null float64
Student/Teacher Ratio          106 non-null float64
Percent Free/Disc Lunch        107 non-null object
Percent African American       107 non-null object
Percent American Indian        107 non-null object
Percent Asian                  107 non-null object
Percent Hispanic               107 non-null object
Percent Pacific Islander       107 non-null object
Percent Two or More Races      107 non-null object
Percent White                  107 non-null object
Average Standard Score         107 non-null float64
Rank Change from Prior Year    100 non-null float64
SchoolDigger Star Rating       107 non-null int64
dtypes: float64(4), int64(4), object(22)
memory usage: 25.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 30 columns):
Rank                           91 non-null int64
Rank_Year                      91 non-null object
School                         91 non-null object
School URL                     91 non-null object
District                       91 non-null object
District URL                   91 non-null object
City                           91 non-null object
City URL                       91 non-null object
Zip                            91 non-null int64
County                         91 non-null object
Low Grade                      91 non-null object
High Grade                     91 non-null int64
Is Title I                     91 non-null object
Is Charter                     91 non-null object
Is Magnet                      91 non-null object
Is Virtual                     91 non-null object
Number Students                91 non-null int64
Number Fulltime Teachers       91 non-null int64
Student/Teacher Ratio          91 non-null float64
Percent Free/Disc Lunch        91 non-null object
Percent African American       91 non-null object
Percent American Indian        91 non-null object
Percent Asian                  91 non-null object
Percent Hispanic               91 non-null object
Percent Pacific Islander       91 non-null object
Percent Two or More Races      91 non-null object
Percent White                  91 non-null object
Average Standard Score         91 non-null float64
Rank Change from Prior Year    89 non-null float64
SchoolDigger Star Rating       91 non-null int64
dtypes: float64(3), int64(6), object(21)
memory usage: 21.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 30 columns):
Rank                           97 non-null int64
Rank_Year                      97 non-null object
School                         97 non-null object
School URL                     97 non-null object
District                       97 non-null object
District URL                   97 non-null object
City                           97 non-null object
City URL                       97 non-null object
Zip                            97 non-null int64
County                         97 non-null object
Low Grade                      97 non-null object
High Grade                     97 non-null int64
Is Title I                     97 non-null object
Is Charter                     97 non-null object
Is Magnet                      97 non-null object
Is Virtual                     97 non-null object
Number Students                97 non-null int64
Number Fulltime Teachers       96 non-null float64
Student/Teacher Ratio          96 non-null float64
Percent Free/Disc Lunch        97 non-null object
Percent African American       97 non-null object
Percent American Indian        97 non-null object
Percent Asian                  97 non-null object
Percent Hispanic               97 non-null object
Percent Pacific Islander       97 non-null object
Percent Two or More Races      97 non-null object
Percent White                  97 non-null object
Average Standard Score         97 non-null float64
Rank Change from Prior Year    85 non-null float64
SchoolDigger Star Rating       97 non-null int64
dtypes: float64(4), int64(5), object(21)
memory usage: 22.8+ KB
None

In [33]:
df_elementary_schools = pd.concat([df_elem_2009_10, df_elem_2010_11,
                                   df_elem_2011_12, df_elem_2013_14,
                                   df_elem_2014_15, df_elem_2015_16], ignore_index = True)

In [34]:
df_middle_schools = pd.concat([df_middle_2009_10, df_middle_2010_11,
                               df_middle_2011_12, df_middle_2013_14,
                               df_middle_2014_15, df_middle_2015_16], ignore_index = True)

In [35]:
df_high_schools = pd.concat([df_high_2009_10, df_high_2010_11,
                             df_high_2011_12, df_high_2013_14,
                             df_high_2014_15, df_high_2015_16], ignore_index = True)

In [36]:
df_elementary_schools.head()

,Rank,Rank_Year,School,School URL,District,District URL,City,City URL,Zip,County,...,Percent African American,Percent American Indian,Percent Asian,Percent Hispanic,Percent Pacific Islander,Percent Two or More Races,Percent White,Average Standard Score,Rank Change from Prior Year,SchoolDigger Star Rating
0,1,2009-10,Key Elementary School,https://www.schooldigger.com/go/DC/schools/000...,District Of Columbia Public Schools,https://www.schooldigger.com/go/DC/district/00...,Washington,https://www.schooldigger.com/go/DC/city/Washin...,20016,District Of Columbia,...,8.5 %,0.0 %,9.6 %,8.2 %,NaN,NaN,73.8 %,98.3,NaN,5
1,2,2009-10,Mann Elementary School,https://www.schooldigger.com/go/DC/schools/000...,District Of Columbia Public Schools,https://www.schooldigger.com/go/DC/district/00...,Washington,https://www.schooldigger.com/go/DC/city/Washin...,20016,District Of Columbia,...,8.2 %,0.0 %,6.7 %,6.3 %,NaN,NaN,78.8 %,98.1,NaN,5
2,3,2009-10,Stoddert Elementary School,https://www.schooldigger.com/go/DC/schools/000...,District Of Columbia Public Schools,https://www.schooldigger.com/go/DC/district/00...,Washington,https://www.schooldigger.com/go/DC/city/Washin...,20007,District Of Columbia,...,19.3 %,0.0 %,11.6 %,8.8 %,NaN,NaN,60.4 %,97.9,NaN,5
3,4,2009-10,Janney Elementary School,https://www.schooldigger.com/go/DC/schools/000...,District Of Columbia Public Schools,https://www.schooldigger.com/go/DC/district/00...,Washington,https://www.schooldigger.com/go/DC/city/Washin...,20016,District Of Columbia,...,14.0 %,0.7 %,6.1 %,5.6 %,NaN,NaN,73.6 %,97.8,NaN,5
4,5,2009-10,St Coletta Special Education Pcs,https://www.schooldigger.com/go/DC/schools/000...,St Coletta Special Education Pcs,https://www.schooldigger.com/go/DC/district/00...,Washington,https://www.schooldigger.com/go/DC/city/Washin...,20003,District Of Columbia,...,88.4 %,0.0 %,0.0 %,6.2 %,NaN,NaN,5.3 %,97.2,NaN,5

In [37]:
# Remove ' %' characters from data
df_elementary_schools['Percent Free/Disc Lunch'] = df_elementary_schools['Percent Free/Disc Lunch'].str.replace(' %','')
df_elementary_schools['Percent African American'] = df_elementary_schools['Percent African American'].str.replace(' %','')
df_elementary_schools['Percent American Indian'] = df_elementary_schools['Percent American Indian'].str.replace(' %','')
df_elementary_schools['Percent Asian'] = df_elementary_schools['Percent Asian'].str.replace(' %','')
df_elementary_schools['Percent Hispanic'] = df_elementary_schools['Percent Hispanic'].str.replace(' %','')
df_elementary_schools['Percent Pacific Islander'] = df_elementary_schools['Percent Pacific Islander'].str.replace(' %','')
df_elementary_schools['Percent Two or More Races'] = df_elementary_schools['Percent Two or More Races'].str.replace(' %','')
df_elementary_schools['Percent White'] = df_elementary_schools['Percent White'].str.replace(' %','')

In [38]:
# Remove ' %' characters from data
df_middle_schools['Percent Free/Disc Lunch'] = df_middle_schools['Percent Free/Disc Lunch'].str.replace(' %','')
df_middle_schools['Percent African American'] = df_middle_schools['Percent African American'].str.replace(' %','')
df_middle_schools['Percent American Indian'] = df_middle_schools['Percent American Indian'].str.replace(' %','')
df_middle_schools['Percent Asian'] = df_middle_schools['Percent Asian'].str.replace(' %','')
df_middle_schools['Percent Hispanic'] = df_middle_schools['Percent Hispanic'].str.replace(' %','')
df_middle_schools['Percent Pacific Islander'] = df_middle_schools['Percent Pacific Islander'].str.replace(' %','')
df_middle_schools['Percent Two or More Races'] = df_middle_schools['Percent Two or More Races'].str.replace(' %','')
df_middle_schools['Percent White'] = df_middle_schools['Percent White'].str.replace(' %','')

In [39]:
# Remove ' %' characters from data
df_high_schools['Percent Free/Disc Lunch'] = df_high_schools['Percent Free/Disc Lunch'].str.replace(' %','')
df_high_schools['Percent African American'] = df_high_schools['Percent African American'].str.replace(' %','')
df_high_schools['Percent American Indian'] = df_high_schools['Percent American Indian'].str.replace(' %','')
df_high_schools['Percent Asian'] = df_high_schools['Percent Asian'].str.replace(' %','')
df_high_schools['Percent Hispanic'] = df_high_schools['Percent Hispanic'].str.replace(' %','')
df_high_schools['Percent Pacific Islander'] = df_high_schools['Percent Pacific Islander'].str.replace(' %','')
df_high_schools['Percent Two or More Races'] = df_high_schools['Percent Two or More Races'].str.replace(' %','')
df_high_schools['Percent White'] = df_high_schools['Percent White'].str.replace(' %','')

In [40]:
# Convert Percentage columns to numeric
df_elementary_schools['Percent Free/Disc Lunch'] = df_elementary_schools['Percent Free/Disc Lunch'].convert_objects(convert_numeric=True)
df_elementary_schools['Percent African American'] = df_elementary_schools['Percent African American'].convert_objects(convert_numeric=True)
df_elementary_schools['Percent American Indian'] = df_elementary_schools['Percent American Indian'].convert_objects(convert_numeric=True)
df_elementary_schools['Percent Asian'] = df_elementary_schools['Percent Asian'].convert_objects(convert_numeric=True)
df_elementary_schools['Percent Hispanic'] = df_elementary_schools['Percent Hispanic'].convert_objects(convert_numeric=True)
df_elementary_schools['Percent Pacific Islander'] = df_elementary_schools['Percent Pacific Islander'].convert_objects(convert_numeric=True)
df_elementary_schools['Percent Two or More Races'] = df_elementary_schools['Percent Two or More Races'].convert_objects(convert_numeric=True)
df_elementary_schools['Percent White'] = df_elementary_schools['Percent White'].convert_objects(convert_numeric=True)

/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:2: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  from ipykernel import kernelapp as app
/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:3: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  app.launch_new_instance()
/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:4: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:5: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:6: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:7: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:8: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:9: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.

In [41]:
# Convert Percentage columns to numeric
df_middle_schools['Percent Free/Disc Lunch'] = df_middle_schools['Percent Free/Disc Lunch'].convert_objects(convert_numeric=True)
df_middle_schools['Percent African American'] = df_middle_schools['Percent African American'].convert_objects(convert_numeric=True)
df_middle_schools['Percent American Indian'] = df_middle_schools['Percent American Indian'].convert_objects(convert_numeric=True)
df_middle_schools['Percent Asian'] = df_middle_schools['Percent Asian'].convert_objects(convert_numeric=True)
df_middle_schools['Percent Hispanic'] = df_middle_schools['Percent Hispanic'].convert_objects(convert_numeric=True)
df_middle_schools['Percent Pacific Islander'] = df_middle_schools['Percent Pacific Islander'].convert_objects(convert_numeric=True)
df_middle_schools['Percent Two or More Races'] = df_middle_schools['Percent Two or More Races'].convert_objects(convert_numeric=True)
df_middle_schools['Percent White'] = df_middle_schools['Percent White'].convert_objects(convert_numeric=True)

/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:2: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  from ipykernel import kernelapp as app
/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:3: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  app.launch_new_instance()
/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:4: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:5: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:6: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:7: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:8: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:9: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.

In [42]:
# Convert Percentage columns to numeric
df_high_schools['Percent Free/Disc Lunch'] = df_high_schools['Percent Free/Disc Lunch'].convert_objects(convert_numeric=True)
df_high_schools['Percent African American'] = df_high_schools['Percent African American'].convert_objects(convert_numeric=True)
df_high_schools['Percent American Indian'] = df_high_schools['Percent American Indian'].convert_objects(convert_numeric=True)
df_high_schools['Percent Asian'] = df_high_schools['Percent Asian'].convert_objects(convert_numeric=True)
df_high_schools['Percent Hispanic'] = df_high_schools['Percent Hispanic'].convert_objects(convert_numeric=True)
df_high_schools['Percent Pacific Islander'] = df_high_schools['Percent Pacific Islander'].convert_objects(convert_numeric=True)
df_high_schools['Percent Two or More Races'] = df_high_schools['Percent Two or More Races'].convert_objects(convert_numeric=True)
df_high_schools['Percent White'] = df_high_schools['Percent White'].convert_objects(convert_numeric=True)

/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:2: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  from ipykernel import kernelapp as app
/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:3: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  app.launch_new_instance()
/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:4: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:5: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:6: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:7: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:8: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
/home/jonathan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:9: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.

In [43]:
df_elementary_schools.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 623 entries, 0 to 622
Data columns (total 30 columns):
Rank                           623 non-null int64
Rank_Year                      623 non-null object
School                         623 non-null object
School URL                     623 non-null object
District                       623 non-null object
District URL                   623 non-null object
City                           623 non-null object
City URL                       623 non-null object
Zip                            623 non-null int64
County                         623 non-null object
Low Grade                      623 non-null object
High Grade                     623 non-null object
Is Title I                     623 non-null object
Is Charter                     623 non-null object
Is Magnet                      623 non-null object
Is Virtual                     623 non-null object
Number Students                623 non-null int64
Number Fulltime Teachers       615 non-null float64
Student/Teacher Ratio          615 non-null float64
Percent Free/Disc Lunch        618 non-null float64
Percent African American       622 non-null float64
Percent American Indian        622 non-null float64
Percent Asian                  622 non-null float64
Percent Hispanic               622 non-null float64
Percent Pacific Islander       514 non-null float64
Percent Two or More Races      514 non-null float64
Percent White                  622 non-null float64
Average Standard Score         623 non-null float64
Rank Change from Prior Year    490 non-null float64
SchoolDigger Star Rating       623 non-null int64
dtypes: float64(12), int64(4), object(14)
memory usage: 146.1+ KB

In [44]:
df_elementary_schools.to_csv('df_elementary_schools.csv')
df_middle_schools.to_csv('df_middle_schools.csv')
df_high_schools.to_csv('df_high_schools.csv')